#!/usr/bin/env python3
"""Build a deterministic signing-key plan from an Android target-files ZIP.

This avoids hard-coding the ever-changing APEX list. It only handles metadata;
private keys are generated by lenos_wizard.sh with OpenSSL.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shlex
import sys
import zipfile
from pathlib import Path
from typing import Any

# Match Lineage/AOSP common.SPECIAL_CERT_STRINGS exactly. Empty private-key
# fields are paired with PRESIGNED/EXTERNAL certificates in apkcerts.txt.
SPECIAL_KEYS = {"", "PRESIGNED", "EXTERNAL"}
SAFE_VALUE = re.compile(r"^[A-Za-z0-9._+/=@:-]+$")
SAFE_APK_NAME = re.compile(r"^[A-Za-z0-9._+@=-]+\.apk$")
SAFE_APEX_NAME = re.compile(r"^[A-Za-z0-9._+-]+\.apex$")
KNOWN_PACKAGE_KEYS = {
    "bluetooth",
    "media",
    "networkstack",
    "nfc",
    "platform",
    "releasekey",
    "sdk_sandbox",
    "shared",
    "testcert",
    "testkey",
    "verity",
}
CORE_PACKAGE_KEYS = [
    "bluetooth",
    "media",
    "networkstack",
    "nfc",
    "platform",
    "releasekey",
    "sdk_sandbox",
    "shared",
]


class MetadataError(RuntimeError):
    pass


def _fields(line: str) -> dict[str, str]:
    result: dict[str, str] = {}
    try:
        tokens = shlex.split(line, posix=True)
    except ValueError as exc:
        raise MetadataError(f"cannot parse metadata line: {line!r}: {exc}") from exc
    for token in tokens:
        if "=" not in token:
            continue
        key, value = token.split("=", 1)
        result[key] = value
    return result


def _strip_key_suffix(path: str) -> str:
    for suffix in (".x509.pem", ".pk8", ".pem", ".avbpubkey"):
        if path.endswith(suffix):
            return path[: -len(suffix)]
    return path


def _validate_value(value: str, label: str) -> None:
    if not SAFE_VALUE.fullmatch(value):
        raise MetadataError(f"unsafe {label}: {value!r}")


def _package_key_id(source_base: str) -> str:
    basename = source_base.rsplit("/", 1)[-1]
    if basename in {"testkey", "devkey", "releasekey"}:
        return "releasekey"
    if basename in KNOWN_PACKAGE_KEYS:
        return basename
    digest = hashlib.sha256(source_base.encode("utf-8")).hexdigest()[:16]
    return f"apk_{digest}"


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def inspect_target(path: Path) -> dict[str, Any]:
    if not path.is_file():
        raise MetadataError(f"target-files ZIP not found: {path}")

    with zipfile.ZipFile(path) as zf:
        names = set(zf.namelist())
        required = {
            "META/ab_partitions.txt",
            "META/apkcerts.txt",
            "META/apexkeys.txt",
            "META/misc_info.txt",
        }
        missing = sorted(required - names)
        if missing:
            raise MetadataError(f"target-files ZIP is missing: {', '.join(missing)}")
        apk_text = zf.read("META/apkcerts.txt").decode("utf-8")
        apex_text = zf.read("META/apexkeys.txt").decode("utf-8")
        partition_text = zf.read("META/ab_partitions.txt").decode("utf-8")
        misc_text = zf.read("META/misc_info.txt").decode("utf-8")

    misc = {}
    for raw in misc_text.splitlines():
        if "=" in raw:
            key, value = raw.split("=", 1)
            misc[key.strip()] = value.strip()
    if misc.get("ab_update") != "true":
        raise MetadataError("target-files metadata does not declare an A/B OTA target")

    ab_partitions: list[str] = []
    for raw in partition_text.splitlines():
        partition = raw.strip()
        if not partition:
            continue
        if not re.fullmatch(r"[a-z0-9_]+", partition):
            raise MetadataError(f"unsafe A/B partition name: {partition!r}")
        ab_partitions.append(partition)
    if not ab_partitions:
        raise MetadataError("META/ab_partitions.txt is empty")

    # META/ab_partitions.txt lists every A/B-updated partition, including
    # vendor firmware (abl, xbl, tz, modem, hyp, ...) that the Android build
    # never gives an AVB footer -- abl, for instance, is a raw ELF. Passing
    # those to `avbroot ota patch --re-sign` fails with
    # "Invalid VBMeta header magic: [127, 69, 76, 70]" ("\x7fELF").
    #
    # AVB-signed partitions are exactly the ones the build system computed a
    # footer/descriptor for, which misc_info.txt records as
    # avb_<partition>_add_hashtree_footer_args / _add_hash_footer_args, plus
    # the vbmeta images themselves (avb_<name>_key_path). Derive the set from
    # that metadata instead of assuming every A/B partition is AVB-signed.
    avb_signed: set[str] = set()
    for key in misc:
        matched = re.fullmatch(
            r"avb_([a-z0-9_]+)_(?:add_hashtree_footer_args|add_hash_footer_args)", key
        )
        if matched:
            avb_signed.add(matched.group(1))
            continue
        matched = re.fullmatch(r"avb_([a-z0-9_]+)_key_path", key)
        if matched and misc.get(key, "").strip():
            avb_signed.add(matched.group(1))
    if misc.get("avb_enable") == "true":
        avb_signed.add("vbmeta")
    resign_partitions = sorted(avb_signed & set(ab_partitions))
    if not resign_partitions:
        raise MetadataError(
            "no AVB-signed A/B partitions found in META/misc_info.txt"
        )

    apk_map: dict[str, str] = {}
    apk_entries: dict[str, str] = {}
    presigned_apks: list[str] = []
    for raw in apk_text.splitlines():
        line = raw.strip()
        if not line:
            continue
        item = _fields(line)
        name = item.get("name", "")
        if not SAFE_APK_NAME.fullmatch(name):
            raise MetadataError(f"unsafe or malformed APK name: {name!r}")
        private = item.get("private_key", "")
        cert = item.get("certificate", "")
        if not private and not cert:
            raise MetadataError(f"APK {name} has no signing metadata")
        private_special = private in SPECIAL_KEYS
        cert_special = cert in SPECIAL_KEYS
        if name in apk_entries or name in presigned_apks:
            raise MetadataError(f"duplicate APK signing metadata for {name}")
        if private_special and cert_special:
            presigned_apks.append(name)
            continue
        if private_special != cert_special:
            raise MetadataError(
                f"APK {name} has only one signable key; refusing an inconsistent override"
            )
        source = _strip_key_suffix(private)
        _validate_value(source, "APK key path")
        key_id = _package_key_id(source)
        previous = apk_map.setdefault(source, key_id)
        if previous != key_id:
            raise MetadataError(f"inconsistent APK key mapping for {source}")
        apk_entries[name] = key_id

    apex_map: dict[str, str] = {}
    presigned_apexes: list[str] = []
    for raw in apex_text.splitlines():
        line = raw.strip()
        if not line:
            continue
        item = _fields(line)
        name = item.get("name", "")
        payload_public = item.get("public_key", "")
        payload_private = item.get("private_key", "")
        container_cert = item.get("container_certificate", "")
        container_private = item.get("container_private_key", "")
        if not any((payload_public, payload_private, container_cert, container_private)):
            raise MetadataError(f"APEX {name or '<unknown>'} has no signing metadata")
        if not SAFE_APEX_NAME.fullmatch(name):
            raise MetadataError(f"unsafe or malformed APEX name: {name!r}")
        if name in apex_map or name in presigned_apexes:
            raise MetadataError(f"duplicate APEX signing metadata for {name}")
        payload_public_special = payload_public in SPECIAL_KEYS
        payload_private_special = payload_private in SPECIAL_KEYS
        container_cert_special = container_cert in SPECIAL_KEYS
        container_private_special = container_private in SPECIAL_KEYS
        if payload_public_special != payload_private_special:
            raise MetadataError(f"APEX {name} has an inconsistent payload key pair")
        if container_cert_special != container_private_special:
            raise MetadataError(f"APEX {name} has an inconsistent container key pair")
        payload_special = payload_private_special
        container_special = container_private_special
        if payload_special and container_special:
            presigned_apexes.append(name)
            continue
        if payload_special != container_special:
            raise MetadataError(
                f"APEX {name} has only one signable key; refusing an inconsistent override"
            )
        _validate_value(payload_public, "APEX payload public-key path")
        _validate_value(payload_private, "APEX payload key path")
        _validate_value(container_cert, "APEX container certificate path")
        _validate_value(container_private, "APEX container key path")
        key_id = name[: -len(".apex")]
        previous = apex_map.setdefault(name, key_id)
        if previous != key_id:
            raise MetadataError(f"inconsistent APEX metadata for {name}")

    package_ids = sorted(set(CORE_PACKAGE_KEYS) | set(apk_map.values()))
    return {
        "schema": 2,
        "target_files": str(path.resolve()),
        "target_files_sha256": _sha256_file(path),
        "ab_partitions": sorted(set(ab_partitions)),
        "resign_partitions": resign_partitions,
        "package_keys": [
            {"source": source, "key_id": key_id}
            for source, key_id in sorted(apk_map.items())
        ],
        "package_key_ids": package_ids,
        "apks": [
            {"name": name, "key_id": key_id}
            for name, key_id in sorted(apk_entries.items())
        ],
        "apexes": [
            {"name": name, "key_id": key_id}
            for name, key_id in sorted(apex_map.items())
        ],
        "presigned_apks": sorted(set(presigned_apks)),
        "presigned_apexes": sorted(set(presigned_apexes)),
    }


def load_plan(path: Path) -> dict[str, Any]:
    try:
        plan = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise MetadataError(f"cannot read signing plan {path}: {exc}") from exc
    if plan.get("schema") != 2:
        raise MetadataError(f"unsupported signing plan schema in {path}")
    if not re.fullmatch(r"[0-9a-f]{64}", str(plan.get("target_files_sha256", ""))):
        raise MetadataError(f"invalid target-files hash in {path}")
    for field in (
        "ab_partitions", "resign_partitions",
        "package_keys", "package_key_ids", "apks", "apexes",
        "presigned_apks", "presigned_apexes",
    ):
        if not isinstance(plan.get(field), list):
            raise MetadataError(f"invalid or missing {field} in {path}")
    return plan


def emit_tsv(plan: dict[str, Any], section: str) -> None:
    if section == "package-ids":
        for key_id in plan["package_key_ids"]:
            print(key_id)
    elif section == "ab-partitions":
        for partition in plan["ab_partitions"]:
            print(partition)
    elif section == "resign-partitions":
        for partition in plan["resign_partitions"]:
            print(partition)
    elif section == "apk-mappings":
        for item in plan["package_keys"]:
            print(f"{item['source']}\t{item['key_id']}")
    elif section == "apex-mappings":
        for item in plan["apexes"]:
            print(f"{item['name']}\t{item['key_id']}")
    else:  # pragma: no cover - guarded by argparse
        raise MetadataError(f"unknown section: {section}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    inspect_p = sub.add_parser("inspect", help="create a signing plan")
    inspect_p.add_argument("target_files", type=Path)
    inspect_p.add_argument("--output", required=True, type=Path)

    emit_p = sub.add_parser("emit", help="emit a plan section as TSV")
    emit_p.add_argument("plan", type=Path)
    emit_p.add_argument(
        "section",
        choices=("package-ids", "ab-partitions", "resign-partitions",
                 "apk-mappings", "apex-mappings"),
    )

    args = parser.parse_args()
    try:
        if args.command == "inspect":
            plan = inspect_target(args.target_files)
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(
                json.dumps(plan, indent=2, sort_keys=True) + "\n", encoding="utf-8"
            )
            print(
                f"plan: {len(plan['package_key_ids'])} package keys, "
                f"{len(plan['apexes'])} signable APEXes, "
                f"{len(plan['presigned_apexes'])} presigned APEXes"
            )
        elif args.command == "emit":
            emit_tsv(load_plan(args.plan), args.section)
    except (MetadataError, KeyError, OSError, zipfile.BadZipFile) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
